version: '2.2'

# For the varibles below: HOSTSIDE:CONTAINER SIDE

services:
  octoprint_wdi3:
    restart: unless-stopped
    container_name: octoprint-docked
    image: octoprint/octoprint
    ports:
      - 80:80
    devices:
      - /dev/ttyUSB0:/dev/ttyACM0
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
    volumes:
     - /home/pi/OCTOPRINT:/octoprint
     - "/etc/localtime:/etc/localtime:ro"
    environment:
      - ENABLE_MJPG_STREAMER=true
      - TZ=America/Chicago